jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx
      - name: Start Docker Compose
        run: docker-compose up -d
      - name: Wait for Keycloak
        run: |
          for i in {1..60}; do
            if curl -s http://localhost:8080/realms/fastapi-library/.well-known/openid-configuration; then
              echo "Keycloak is up!"
              break
            fi
            echo "Waiting for Keycloak..."
            sleep 2
          done
      - name: Wait for FastAPI
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8000/docs; then
              echo "FastAPI is up!"
              break
            fi
            echo "Waiting for FastAPI..."
            sleep 2
          done
      - name: Run tests
        run: pytest tests/